/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WDEMO3_H
#define XTCW_WDEMO3_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNlang
#define XtNlang "lang"
#endif
#ifndef XtCLang
#define XtCLang "Lang"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNfontName
#define XtNfontName "fontName"
#endif
#ifndef XtCFontName
#define XtCFontName "FontName"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNbackground
#define XtNbackground "background"
#endif
#ifndef XtCBackground
#define XtCBackground "Background"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

typedef struct _Wdemo3ClassRec *Wdemo3WidgetClass;
typedef struct _Wdemo3Rec *Wdemo3Widget;
externalref WidgetClass wdemo3WidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WDEMO3_H */
